In [2]:
import torch
import tqdm as tqdm

In [3]:
def describe(x):
    print(f"Type: {x.type()}")
    print(f"Shape: {x.shape}")
    print(f"Values: {x}")

In [4]:
describe(torch.Tensor(2, 3))

Type: torch.FloatTensor
Shape: torch.Size([2, 3])
Values: tensor([[-5.6663e+04,  8.0435e-43, -5.6665e+04],
        [ 8.0435e-43, -5.6669e+04,  8.0435e-43]])


In [5]:
describe(torch.rand(2, 3)) # равномерное
describe(torch.randn(2, 3)) # нормальное

Type: torch.FloatTensor
Shape: torch.Size([2, 3])
Values: tensor([[0.7220, 0.5205, 0.7625],
        [0.8690, 0.4212, 0.9375]])
Type: torch.FloatTensor
Shape: torch.Size([2, 3])
Values: tensor([[ 1.2513,  0.9662, -0.2057],
        [ 0.5396,  0.3484,  1.2224]])


In [6]:
describe(torch.zeros(2, 3))
x = torch.ones(2, 3)
describe(x)
x.fill_(5)
describe(x)

Type: torch.FloatTensor
Shape: torch.Size([2, 3])
Values: tensor([[0., 0., 0.],
        [0., 0., 0.]])
Type: torch.FloatTensor
Shape: torch.Size([2, 3])
Values: tensor([[1., 1., 1.],
        [1., 1., 1.]])
Type: torch.FloatTensor
Shape: torch.Size([2, 3])
Values: tensor([[5., 5., 5.],
        [5., 5., 5.]])


In [7]:
import numpy as np

In [8]:
npy = np.random.rand(2, 3)
describe(torch.from_numpy(npy))

Type: torch.DoubleTensor
Shape: torch.Size([2, 3])
Values: tensor([[0.4144, 0.7654, 0.0345],
        [0.0470, 0.7744, 0.7914]], dtype=torch.float64)


In [10]:
describe(torch.Tensor(2, 3))
describe(torch.DoubleTensor(2, 3))

Type: torch.FloatTensor
Shape: torch.Size([2, 3])
Values: tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 8.0435e-43]])
Type: torch.DoubleTensor
Shape: torch.Size([2, 3])
Values: tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)


In [12]:
x = torch.arange(6)
x

tensor([0, 1, 2, 3, 4, 5])

In [15]:
x = x.view(2, 3)
x

tensor([[0, 1, 2],
        [3, 4, 5]])

In [16]:
torch.sum(x, dim=0)

tensor([3, 5, 7])

In [17]:
torch.transpose(x, 0, 1)

tensor([[0, 3],
        [1, 4],
        [2, 5]])

In [20]:
x = torch.arange(6).view(2, 3)
x

tensor([[0, 1, 2],
        [3, 4, 5]])

In [19]:
x[:1, :2]

tensor([[0, 1]])

In [21]:
indices = torch.LongTensor([0, 2])
torch.index_select(x, dim=1, index=indices)

tensor([[0, 2],
        [3, 5]])

In [22]:
indices = torch.LongTensor([0, 0])
torch.index_select(x, dim=0, index=indices)

tensor([[0, 1, 2],
        [0, 1, 2]])

In [23]:
torch.cat([x, x], dim=0)

tensor([[0, 1, 2],
        [3, 4, 5],
        [0, 1, 2],
        [3, 4, 5]])

In [24]:
torch.cat([x, x], dim=1)

tensor([[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5]])

In [25]:
torch.stack([x, x])

tensor([[[0, 1, 2],
         [3, 4, 5]],

        [[0, 1, 2],
         [3, 4, 5]]])

In [40]:
x = torch.ones(2, 2, requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [41]:
print(x.grad)

None


In [42]:
y = (x + 2) * (x + 5) + 3

In [43]:
z = y.mean()
z.backward()
print(x.grad)

tensor([[2.2500, 2.2500],
        [2.2500, 2.2500]])


In [44]:
print(torch.cuda.is_available())

False


# Tasks

In [48]:
# 1
x = torch.rand(3, 3)
print(x.shape)
x = x[None, :]
print(x.shape)

torch.Size([3, 3])
torch.Size([1, 3, 3])


In [53]:
# 1
x = torch.rand(3, 3)
print(x.shape)
x = torch.unsqueeze(x, dim=0)
print(x.shape)

torch.Size([3, 3])
torch.Size([1, 3, 3])


In [54]:
# 2
print(x.shape)
x = x.squeeze()
print(x.shape)

torch.Size([1, 3, 3])
torch.Size([3, 3])


In [59]:
# 3
x = torch.randint(3, 7, size=(5, 3))
x

tensor([[5, 5, 5],
        [6, 4, 5],
        [4, 6, 5],
        [3, 6, 5],
        [5, 4, 6]])

In [63]:
# 4
x = torch.randn(3, 3)
x

tensor([[ 1.2663,  1.4032, -0.4668],
        [ 1.2166, -0.0496,  0.1831],
        [ 1.2312, -0.8972, -3.1487]])

In [64]:
# 5
x = torch.Tensor([1, 1, 1, 0, 1])
x[x != 0]

tensor([1., 1., 1., 1.])

In [68]:
# 6
x = torch.rand(3, 1)
torch.stack([x, x, x, x], dim=0).T

tensor([[[0.5201, 0.5201, 0.5201, 0.5201],
         [0.7716, 0.7716, 0.7716, 0.7716],
         [0.5389, 0.5389, 0.5389, 0.5389]]])

In [69]:
# 7
torch.matmul(torch.rand(3, 4, 5), torch.rand(3, 5, 4))

tensor([[[2.3826, 2.2595, 1.3035, 1.5655],
         [2.0112, 1.8053, 0.9756, 1.5253],
         [2.1088, 1.9377, 1.3064, 1.2981],
         [2.1117, 2.1240, 1.0955, 1.3038]],

        [[1.1192, 1.2231, 2.0823, 2.0639],
         [0.8776, 0.8773, 1.5964, 1.5463],
         [0.4776, 0.5051, 1.1456, 0.9811],
         [1.3384, 0.9890, 1.3301, 1.8696]],

        [[1.3464, 1.1694, 0.7347, 1.3401],
         [2.1030, 1.5618, 1.1161, 2.0452],
         [1.7071, 1.2554, 1.1232, 1.6751],
         [1.7295, 1.8048, 0.8316, 1.9562]]])

In [70]:
# 8
torch.matmul(torch.rand(3, 4, 5), torch.rand(5, 4))

tensor([[[0.8033, 0.3665, 0.3827, 1.0088],
         [1.9270, 1.1158, 0.9574, 1.4911],
         [0.2778, 0.1666, 0.1241, 0.1023],
         [0.4030, 0.3784, 0.4685, 0.5610]],

        [[0.9996, 0.7663, 0.7476, 0.8813],
         [1.8928, 1.2114, 1.1104, 1.7275],
         [0.8622, 0.6801, 0.6914, 0.7740],
         [1.5070, 0.8341, 0.7497, 1.5381]],

        [[0.9887, 0.6730, 0.6988, 1.1249],
         [0.8380, 0.5385, 0.5148, 0.5531],
         [1.6378, 1.1289, 1.0819, 1.4541],
         [0.8850, 0.3532, 0.3451, 1.0392]]])